<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Co extends Doctor_controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Co_model');
    } 

    /*
     * Listing of co_master
     */
    function index()
    {
		$this->view_data['co_master'] = $this->Co_model->get_all_co_master($this->user_data->id);

		$this->view_data['_view'] = 'doctor/co/index';
        $this->load->view('layouts/master_page_doctors',$this->view_data);
    }

    /*
     * Adding a new co_master
     */
    function add()
    {

        $this->load->library('form_validation');
		if($this->form_validation->run('co'))
        {   
            $params = array(
				'co_code' => $this->input->post('co_code'),
				'created_by' => $this->user_data->id,
				'doctor_id' => $this->user_data->id,
				'status' => "Active",
				'created_at' => date('Y-m-d H:i:s'),
				'updated_at' => date('Y-m-d H:i:s'),
				'co_detail' => $this->input->post('co_detail'),
            );
            
            $co_master_id = $this->Co_model->add_co_master($params);
            if ($co_master_id){
				$this->_alertSuccessResponce(true,"Co Inserted", "Co Not Inserted", "doctor/co/index");

			}
            else{
				$this->_alertSuccessResponce(false,"Co Inserted", "Co Not Inserted", "doctor/co/index");

			}

        }
        else
        {
			$this->view_data['_view'] = 'doctor/co/add';
            $this->load->view('layouts/master_page_doctors',$this->view_data);
        }
    }  

    /*
     * Editing a co_master
     */
    function edit($id)
    {   
        // check if the co_master exists before trying to edit it
		$this->view_data['co_master'] = $this->Co_model->get_co_master($id,$this->user_data->id);
        
        if(isset($this->view_data['co_master']['id']))
        {
            $this->load->library('form_validation');


			if($this->form_validation->run('co'))
            {
				$params = array(
					'co_code' => $this->input->post('co_code'),
					'updated_at' => date('Y-m-d H:i:s'),
					'co_detail' => $this->input->post('co_detail'),
				);

                $this->Co_model->update_co_master($id,$params);
				$this->_alertSuccessResponce(true, "Co updated.", "Co not updated..", "doctor/co/index");


            }
            else
            {
				$this->view_data['_view'] = 'doctor/co/edit';
                $this->load->view('layouts/master_page_doctors',$this->view_data);
            }
        }
        else
            show_error('The co_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting co_master
     */
    function remove($id)
    {
        $co_master = $this->Co_model->get_co_master($id,$this->user_data->id);

        // check if the co_master exists before trying to delete it
        if(isset($co_master['id']))
        {
            $this->Co_model->delete_co_master($id);
			$this->_alertSuccessResponce(true, "Co Deleted.", "Co not Deleted..", "doctor/co/index");


        }
        else
            show_error('The co_master you are trying to delete does not exist.');
    }
    
}
