<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Label extends Doctor_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Label_model');
    } 

    /*
     * Listing of label_master
     */
    function index()
    {
        $this->view_data['label_master'] = $this->Label_model->get_all_label_master($this->user_data->id);
        
        $this->view_data['_view'] = 'doctor/label/index';
        $this->load->view('layouts/master_page_doctors',$this->view_data);
    }

    /*
     * Adding a new label_master
     */
    function add()
    {   
        $this->load->library('form_validation');


		if($this->form_validation->run('label'))
        {   
            $params = array(
				'label_title' => $this->input->post('label_title'),
				'label_unit' => $this->input->post('label_unit'),
				'created_by' => $this->user_data->id,
				'doctor_id' => $this->user_data->id,
				'status' => "Active",
				'created_at' => date('Y-m-d H:i:s'),
				'updated_at' => date('Y-m-d H:i:s'),
				'input_type'=>"text_box",

            );
            
            $label_master_id = $this->Label_model->add_label_master($params);
			$this->_alertSuccessResponce(true, "Label Inserted.", "Label not Inserted..", "doctor/label/index");


        }
        else
        {            
            $this->view_data['_view'] = 'doctor/label/add';
            $this->load->view('layouts/master_page_doctors',$this->view_data);
        }
    }  

    /*
     * Editing a label_master
     */
    function edit($id)
    {   
        // check if the label_master exists before trying to edit it
        $this->view_data['label_master'] = $this->Label_model->get_label_master($id,$this->user_data->id);
        
        if(isset($this->view_data['label_master']['id']))
        {
            $this->load->library('form_validation');


			if($this->form_validation->run('label'))
            {   
                $params = array(
					'label_title' => $this->input->post('label_title'),
					'label_unit' => $this->input->post('label_unit'),
					'updated_at' => date('Y-m-d H:i:s'),
                );

                $this->Label_model->update_label_master($id,$params);
				$this->_alertSuccessResponce(true, "Label Updated.", "Label not Updated..", "doctor/label/index");


            }
            else
            {
                $this->view_data['_view'] = 'doctor/label/edit';
                $this->load->view('layouts/master_page_doctors',$this->view_data);
            }
        }
        else
            show_error('The label_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting label_master
     */
    function remove($id)
    {
        $label_master = $this->Label_model->get_label_master($id,$this->user_data->id);

        // check if the label_master exists before trying to delete it
        if(isset($label_master['id']))
        {
            $this->Label_model->delete_label_master($id);
			$this->_alertSuccessResponce(true, "Label Deleted.", "Label not Deleted..", "doctor/label/index");


        }
        else
            show_error('The label_master you are trying to delete does not exist.');
    }
    
}
