<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class P_other_setting extends Doctor_controller {
    function __construct()
    {
        parent::__construct();
        $this->load->model('P_other_setting_model');
    } 

    /*
     * Listing of p_other_settings
     */
    function index()
    {
        $this->view_data['p_other_settings'] = $this->P_other_setting_model->get_all_p_other_settings($this->user_data->id);
        
        $this->view_data['_view'] = 'doctor/p_other_setting/index';
        $this->load->view('layouts/master_page_doctors',$this->view_data);
    }

    /*
     * Adding a new p_other_setting
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('time','Time','required');

		if($this->form_validation->run())     
        {
			$logo="";
			if (!empty($_FILES['logo']['name'])) {
				$profData = $this->_upload_file("upload/p_logo/", date("Y-m-d") . "_" . $this->user_data->id, "logo");
				if ($profData['status'] == 'true') {
					$logo = $profData['file_name'];
				} else {
					return $this->_alertSuccessResponce(FALSE, "Imgs", $profData['upload_error'], "doctor/p_other_setting");
				}
			}
			$full_header="";
			if (!empty($_FILES['full_header']['name'])) {
				$profData = $this->_upload_file("upload/p_logo/", date("Y-m-d") . "_" . $this->user_data->id, "full_header");
				if ($profData['status'] == 'true') {
					$full_header = $profData['file_name'];
				} else {
					return $this->_alertSuccessResponce(FALSE, "Imgs", $profData['upload_error'], "doctor/p_other_setting");
				}
			}
				$params = array(
					'logo' => $logo,
					'full_header'=>$full_header,
					'time' => $this->input->post('time'),
					'header' => $this->input->post('header'),
					'is_full_header'=>$this->input->post('is_full_header'),
					'created_by' => $this->user_data->id,
					'doctor_id' => $this->user_data->id,
					'created_at' => date('Y-m-d H:i:s'),
					'updated_at' => date('Y-m-d H:i:s'),
				);
            $p_other_setting_id = $this->P_other_setting_model->add_p_other_setting($params);
            redirect('doctor/p_other_setting/index');

        }
        else
        {            
            $this->view_data['_view'] = 'doctor/p_other_setting/add';
            $this->load->view('layouts/master_page_doctors',$this->view_data);
        }
    }  

    /*
     * Editing a p_other_setting
     */
    function edit($id)
    {   
        // check if the p_other_setting exists before trying to edit it
        $this->view_data['p_other_setting'] = $this->P_other_setting_model->get_p_other_setting($id,$this->user_data->id);

        if(isset($this->view_data['p_other_setting']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('time','Time','required');

			if($this->form_validation->run())     
            {


				if (!empty($_FILES['full_header']['name'])) {
					$profData = $this->_upload_file("upload/p_logo/", date("Y-m-d") . "_" . $this->user_data->id, "full_header");
					if ($profData['status'] == 'true') {
						$full_header = $profData['file_name'];
					} else {
						return $this->_alertSuccessResponce(FALSE, "Imgs", $profData['upload_error'], "doctor/p_other_setting");
					}

					if ($this->view_data['p_other_setting']['full_header'] != '') {
						unlink("upload/p_logo/" . $this->view_data['p_other_setting']['full_header']);
					}
				}
				else{
					$full_header=$this->view_data['p_other_setting']['full_header'];
				}

				if (!empty($_FILES['logo']['name'])) {
					$profData = $this->_upload_file("upload/p_logo/", date("Y-m-d") . "_" . $this->user_data->id, "logo");
					if ($profData['status'] == 'true') {
						$logo = $profData['file_name'];

						if ($this->view_data['p_other_setting']['logo'] != '') {
							unlink("upload/p_logo/" . $this->view_data['p_other_setting']['logo']);
						}


						$params = array(
							'logo'=>$logo,
							'full_header'=>$full_header,
							'time' => $this->input->post('time'),
							'header' => $this->input->post('header'),
							'is_full_header'=>$this->input->post('is_full_header'),
							'updated_at' => date('Y-m-d H:i:s'),
						);
					} else {
						return $this->_alertSuccessResponce(FALSE, "Imgs", $profData['upload_error'], "doctor/p_other_setting");
					}
				} else {
					$params = array(
						'full_header'=>$full_header,
						'time' => $this->input->post('time'),
						'is_full_header'=>$this->input->post('is_full_header'),
						'header' => $this->input->post('header'),
						'updated_at' => date('Y-m-d H:i:s'),
					);
				}
                $this->P_other_setting_model->update_p_other_setting($id,$params);            
                redirect('doctor/p_other_setting/index');
            }
            else
            {
                $this->view_data['_view'] = 'doctor/p_other_setting/edit';
                $this->load->view('layouts/master_page_doctors',$this->view_data);
            }
        }
        else
            show_error('The p_other_setting you are trying to edit does not exist.');
    } 

    /*
     * Deleting p_other_setting
     */
    function remove($id)
    {
        $p_other_setting = $this->P_other_setting_model->get_p_other_setting($id,$this->user_data->id);

        // check if the p_other_setting exists before trying to delete it
        if(isset($p_other_setting['id']))
        {
            $this->P_other_setting_model->delete_p_other_setting($id,$this->user_data->id);
            redirect('doctor/p_other_setting/index');
        }
        else
            show_error('The p_other_setting you are trying to delete does not exist.');
    }
    
}
