<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Questions extends Doctor_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Questions_model');
		$this->load->model('Co_model');
    } 

    /*
     * Listing of questions_master
     */
    function index()
    {
        $this->view_data['questions_master'] = $this->Questions_model->get_all_questions_master($this->user_data->id);
        
        $this->view_data['_view'] = 'doctor/questions/index';
        $this->load->view('layouts/master_page_doctors',$this->view_data);
    }

    /*
     * Adding a new questions_master
     */
    function add()
    {   
        $this->load->library('form_validation');


		if($this->form_validation->run('questions'))
        {   
            $params = array(
				'question' => $this->input->post('question'),
				'explenations' => $this->input->post('explenations'),
				'co_id' => $this->input->post('co_id'),
				'question_code' => $this->input->post('question_code'),
				'created_by' => $this->user_data->id,
				'doctor_id' => $this->user_data->id,
				'status' => "Active",
				'created_at' => date('Y-m-d H:i:s'),
				'updated_at' => date('Y-m-d H:i:s'),

            );
            
            $questions_master_id = $this->Questions_model->add_questions_master($params);
			$this->_alertSuccessResponce(true, "Question Inserted.", "Question not Deleted..", "doctor/questions/index");


        }
        else
        {
			$this->view_data['co_masters'] = $this->Co_model->get_all_co_master($this->user_data->id);
			$this->view_data['_view'] = 'doctor/questions/add';
            $this->load->view('layouts/master_page_doctors',$this->view_data);
        }
    }  

    /*
     * Editing a questions_master
     */
    function edit($id)
    {   
        // check if the questions_master exists before trying to edit it
        $this->view_data['questions_master'] = $this->Questions_model->get_questions_master($id,$this->user_data->id);
        
        if(isset($this->view_data['questions_master']['id']))
        {
            $this->load->library('form_validation');


			if($this->form_validation->run('questions'))
            {   
                $params = array(
					'question' => $this->input->post('question'),
					'explenations' => $this->input->post('explenations'),
					'updated_at' => date('Y-m-d H:i:s'),
					'co_id' => $this->input->post('co_id'),
					'question_code' => $this->input->post('question_code'),
                );

                $this->Questions_model->update_questions_master($id,$params);
				$this->_alertSuccessResponce(true, "Question Updated.", "Question not Updated..", "doctor/questions/index");


            }
            else
            {
				$this->view_data['co_masters'] = $this->Co_model->get_all_co_master($this->user_data->id);

				$this->view_data['_view'] = 'doctor/questions/edit';
                $this->load->view('layouts/master_page_doctors',$this->view_data);
            }
        }
        else
            show_error('The question you are trying to edit does not exist.');
    } 

    /*
     * Deleting questions_master
     */
    function remove($id)
    {
        $questions_master = $this->Questions_model->get_questions_master($id,$this->user_data->id);

        // check if the questions_master exists before trying to delete it
        if(isset($questions_master['id']))
        {
            $this->Questions_model->delete_questions_master($id);
			$this->_alertSuccessResponce(true, "Question Deleted.", "Question not Deleted..", "doctor/questions/index");


        }
        else
            show_error('The questions_master you are trying to delete does not exist.');
    }
    
}
