<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Table_master extends Doctor_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Table_master_model');
	}

	/*
	 * Listing of table_master
	 */
	function index()
	{
		$this->view_data['table_master'] = $this->Table_master_model->get_all_table_master($this->user_data->id);

		$this->view_data['_view'] = 'doctor/table_master/index';
		$this->load->view('layouts/master_page_doctors', $this->view_data);
	}

	/*
	 * Adding a new table_master
	 */
	function add()
	{
		$this->load->library('form_validation');

		$this->form_validation->set_rules('row', 'Row', 'required|numeric');
		$this->form_validation->set_rules('column', 'Column', 'required|numeric');

		if ($this->form_validation->run()) {

			$lableHeaders =explode(',', $this->input->post('lable_header'));

			foreach ($lableHeaders as $key => $header) {
				if ($header == "") {
					$lableHeaders[$key] = "-";
				}
			}
			$lableFooter = explode(',',$this->input->post('lable_footer'));
//			foreach ($lableFooter as $key => $header) {
//				if ($header == "") {
//					$lableFooter[$key] = "-";
//				}
//			}
			$lableRow = explode(',',$this->input->post('lable_row'));
			foreach ($lableRow as $key => $header) {
				if ($header == "") {
					$lableRow[$key] = "-";
				}
			}

			$params = array(
				'row' => $this->input->post('row'),
				'table_column' => $this->input->post('column'),
				'extra_label' => $this->input->post('extra_label'),
				'lable_header' => json_encode($lableHeaders),
				'lable_footer' => json_encode($lableFooter),
				'lable_row' => json_encode($lableRow),
				'created_by' => $this->user_data->id,
				'doctor_id' => $this->user_data->id,
				'status' => "Active",
				'created_at' => date('Y-m-d H:i:s'),
				'updated_at' => date('Y-m-d H:i:s'),
			);

			$table_master_id = $this->Table_master_model->add_table_master($params);
			redirect('doctor/table_master/index');
			$this->_alertSuccessResponce(true, "Table Inserted.", "Table not Inserted..", "doctor/table_master/index");

		} else {
			$this->view_data['_view'] = 'doctor/table_master/add';
			$this->load->view('layouts/master_page_doctors', $this->view_data);
		}
	}

	/*
	 * Editing a table_master
	 */
	function edit($id)
	{
		// check if the table_master exists before trying to edit it
		$this->view_data['table_master'] = $this->Table_master_model->get_table_master($id, $this->user_data->id);

		if (isset($this->view_data['table_master']['id'])) {
			$this->load->library('form_validation');

			$this->form_validation->set_rules('row', 'Row', 'required|numeric');
			$this->form_validation->set_rules('column', 'Column', 'required|numeric');

			if ($this->form_validation->run()) {

				$lableHeaders =explode(',', $this->input->post('lable_header'));

				foreach ($lableHeaders as $key => $header) {
					if ($header == "") {
						$lableHeaders[$key] = "-";
					}
				}
				$lableFooter = explode(',',$this->input->post('lable_footer'));
//				foreach ($lableFooter as $key => $header) {
//					if ($header == "") {
//						$lableFooter[$key] = "-";
//					}
//				}
				$lableRow = explode(',',$this->input->post('lable_row'));
				foreach ($lableRow as $key => $header) {
					if ($header == "") {
						$lableRow[$key] = "-";
					}
				}
				$params = array(
					'row' => $this->input->post('row'),
					'table_column' => $this->input->post('column'),
					'lable_header' => json_encode($lableHeaders),
					'lable_footer' => json_encode($lableFooter),
					'lable_row' => json_encode($lableRow),
					'extra_label' => $this->input->post('extra_label'),
				);

				$this->Table_master_model->update_table_master($id, $params);
				$this->_alertSuccessResponce(true, "Table Updated.", "Table not Updated..", "doctor/table_master/index");


			} else {
				$this->view_data['_view'] = 'doctor/table_master/edit';
				$this->load->view('layouts/master_page_doctors', $this->view_data);
			}
		} else
			show_error('The table_master you are trying to edit does not exist.');
	}

	/*
	 * Deleting table_master
	 */
	function remove($id)
	{
		$table_master = $this->Table_master_model->get_table_master($id, $this->user_data->id);

		// check if the table_master exists before trying to delete it
		if (isset($table_master['id'])) {
			$this->Table_master_model->delete_table_master($id);
			$this->_alertSuccessResponce(true, "Table Deleted.", "Question not Deleted..", "doctor/table_master/index");

		} else
			show_error('The table_master you are trying to delete does not exist.');
	}

	public function get_table()
	{
		$this->view_data["label_row"] = $this->input->post('label_row');
		$this->view_data["label_header"] = $this->input->post('label_header');
		$this->view_data["label_footer"] =$this->input->post('label_footer');
		$this->view_data["extra_label"] =$this->input->post('extra_label');
		$this->load->view('doctor/table_master/get_table_preview',$this->view_data);

	}

}
