<div class="my-3 my-md-5">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Privacy Policy</h3>
            </div>
            <div class="card-body">
                <h3>Overview</h3>
                <p> This User Privacy Policy describes how Doctorooms website (www.doctorooms.com) (hereinafter referred to as “Website”), e-mail, SMS or any other medium through which Doctorooms may provide services collects, uses and discloses information. Reference to the term Website in this privacy policy shall be applicable mutatis mutandis to e-mail, SMS, application, or any other medium in which Doctorooms (hereinafter referred to as “we”) may provide services. When we say “you” (or similar pronouns) below, we are referring to Users. Your privacy is very important to us. Please read this privacy policy to learn more about the ways in which we use and protect your personal information.
                By visiting our Website you agree to be bound by the terms and conditions of this Privacy Policy. By accepting the Privacy Policy you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms of Service and Legal Use Policy.
               </p>
                <h3>Collection of Information</h3>
                <p> If you browse through this Website with or without providing us with any personal information, we may gather and store some information about your visit, such as IP address, type of browser and operating system used, date and time you access our Website, pages you visit, and if you are linked to our Website from another website, the address of that website etc. There will be times, such as when you fill out our registration/contact form, submit a request or when we will need to obtain personally identifiable information from you or about you; such personally identifiable information may, include but not limited to, your name, address, e-mail address, telephone number, interests, educational details, professional details and identification number etc.</p>
                <p>If you choose to share any content in any form on Website, we will collect that information you provide to us. We retain this information as necessary to provide customer support, to meet our business objectives, resolve disputes or compliance of regulatory requirements. If you send us personal correspondence, such as emails or letters, or if other Users or third parties send us correspondence about your activities or postings on the Website, we may collect such information specific to you.</p>
                <h3> Use and Sharing of Information</h3>
                <p>At no time we shall sell your personally-identifiable data without your permission unless set forth in this Privacy Policy. The information we receive about you or from you may be used by us or shared by us with our corporate affiliates, doctors, hospitals, clinics, dealers, agents, vendors and other third parties to help process your request, to comply with any law, regulation, audit or court order; to help improve our website or the products or services We offer; for research, to better understand our customers' needs; to develop new offerings; and to alert you to new products and services (of us or our business associates). We may also combine information you provide us with information about you that is available to us internally or from other sources in order to serve you better.</p>
                <p>You agree that we may use personal information about you to improve our marketing and promotional efforts, to analyze Website usage, improve the Website's content and product offerings, and customize the Website's content, layout, and services. These uses improve the Website and better tailor it to meet your needs, so as to provide you with a smooth, efficient, safe and customized experience while using the Website.</p>
                <p>You agree that we may use your personal information to contact you and deliver information to you that, in some cases, are targeted to your interests, such as targeted banner advertisements, administrative notices, product offerings, and communications relevant to your use of the Website. By accepting the User Agreement and Privacy Policy, you expressly agree to receive this information. If you do not wish to receive these communications, we encourage you to opt out of the receipt of certain communications in your profile. You may make subscription changes to your profile at any time.</p>
                <h3>Cookies</h3>
                <p> From time to time, we may place "cookies" on your personal computer. "Cookies" are small identifiers sent from a web server and stored on your computer's hard drive, that help us to recognize you if you visit our Website again. Also, our site uses cookies to track how you found our site. You have the ability to accept or decline cookies. Most web browsers automatically accept cookies, but you may modify your browser setting to decline cookies, if you so prefer. If you choose to decline cookies certain features of the site may not function property or at all as a result. We do not control the use of cookies by third parties.</p>
                <h3> Links</h3>
                <p> Our website contains links to other websites. Such other websites may use information about your visit to our website. Our Privacy Policy does not apply to practices of such websites that we do not own or control or to people we do not employ. Therefore, we shall neither be responsible nor shall indemnify in any manner whatsoever, for the practices or the accuracy or the integrity of the content included on such other websites. We encourage you to read the individual privacy statements of such websites.</p>
                <h3>Legal Requests</h3>
                <p>We cooperate with law enforcement agencies and regulatory inquiries, as well as other third parties to enforce laws, such as: intellectual property rights, fraud and other rights, to help protect you and the community from bad actors. Therefore, in response to a verified request by any law enforcement agency or any other government officials relating to a criminal investigation or alleged illegal activity, we can (and you authorize us to) disclose your personal information including but not limited to, name, city, state, telephone number, e-mail address, Website use history and previous fraud complaints, if any pursuant to a summons, court order or substantially similar legal procedure. Further, we can (and you authorise us to) disclose your personal information including but not limited to, name, street address, city, state, zip code, country, phone number, email, and name to Intellectual Property right's owners, as we in our sole discretion believe necessary or appropriate in connection with an investigation of possible fraud, intellectual property infringement, piracy, or any other unlawful activity.</p>
                <h3>Users must be person competent to contract</h3>
                <p> A person competent to contract (as defined by the section 11 of the Indian Contract Act, 1872) only are eligible to use our Website and we ask that a person incompetent to contract not to submit any personal information to us. If you are a person incompetent to contract, you cannot undertake any commercial or non-commercial transaction on the Website. In an event that a person incompetent to contract submits any personal information to us and/or does any transaction etc. then guardians of such person shall be held solely responsible for the same and indemnify us.
                Security</p>
                <p> We safeguard your privacy using known security standards and procedures and comply with applicable privacy laws. Our website combine physical, electronic and procedural safeguards to ensure that your information is well protected though it's life cycle in our infrastructure. Our Website has security measures in place to protect the loss, misuse, and alteration of the information under our control. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access.</p>
                <h3> Changes to this Privacy Policy</h3>
                <p>Our privacy policy is subject to change at any time without notice. To make sure you are aware of the changes, we request you to please review this policy periodically. The updated Privacy Policy will be binding upon you as and when updated.</p>
                <h3>Grievance Officer</h3>
                <p>In accordance with Information Technology Act, 2000 and rules made there under, the name and contact details of the Grievance Officer are hereby published on the Website as below:</p>
                <br>
                <b>Aditya Joshi</b>
                <p> +91 9106096745</p>
                <p><a href="mail:to"> ksv1619aditya@gmail.com</a></p>


            </div>
        </div>
    </div>
</div>
