<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Co_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get co_master by id
     */
    function get_co_master($id,$doctor_id)
    {
        return $this->db->get_where('co_master',array('id'=>$id,'doctor_id'=>$doctor_id))->row_array();
    }
        
    /*
     * Get all co_master
     */
    function get_all_co_master($doctor_id)
    {
        $this->db->order_by('id', 'desc');
		$this->db->where('doctor_id', $doctor_id);
        return $this->db->get('co_master')->result_array();
    }
        
    /*
     * function to add new co_master
     */
    function add_co_master($params)
    {
        $this->db->insert('co_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update co_master
     */
    function update_co_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('co_master',$params);
    }
    
    /*
     * function to delete co_master
     */
    function delete_co_master($id)
    {
        return $this->db->delete('co_master',array('id'=>$id));
    }
}
