<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Label_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get label_master by id
     */
    function get_label_master($id,$doctor_id)
    {
        return $this->db->get_where('label_master',array('id'=>$id,'doctor_id'=>$doctor_id))->row_array();
    }
        
    /*
     * Get all label_master
     */
    function get_all_label_master($doctor_id)
    {
        $this->db->order_by('id', 'desc');
		$this->db->where('doctor_id', $doctor_id);
        return $this->db->get('label_master')->result_array();
    }
        
    /*
     * function to add new label_master
     */
    function add_label_master($params)
    {
        $this->db->insert('label_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update label_master
     */
    function update_label_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('label_master',$params);
    }
    
    /*
     * function to delete label_master
     */
    function delete_label_master($id)
    {
        return $this->db->delete('label_master',array('id'=>$id));
    }
}
