<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class P_other_setting_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get p_other_setting by id
     */
    function get_p_other_setting($id,$doctor_id)
    {
        return $this->db->get_where('p_other_settings',array('id'=>$id,'doctor_id'=>$doctor_id))->row_array();
    }
        
    /*
     * Get all p_other_settings
     */
    function get_all_p_other_settings($doctor_id)
    {
        $this->db->order_by('id', 'desc');
		$this->db->where('doctor_id', $doctor_id);
        return $this->db->get('p_other_settings')->result_array();
    }
        
    /*
     * function to add new p_other_setting
     */
    function add_p_other_setting($params)
    {
        $this->db->insert('p_other_settings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update p_other_setting
     */
    function update_p_other_setting($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('p_other_settings',$params);
    }
    
    /*
     * function to delete p_other_setting
     */
    function delete_p_other_setting($id,$doctor_id)
    {
        return $this->db->delete('p_other_settings',array('id'=>$id,'doctor_id'=>$doctor_id));
    }
}
