<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Questions_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get questions_master by id
     */
    function get_questions_master($id,$doctor_id)
    {
        return $this->db->get_where('questions_master',array('id'=>$id,'doctor_id'=>$doctor_id))->row_array();
    }
        
    /*
     * Get all questions_master
     */
    function get_all_questions_master($doctor_id)
    {
		$this->db->select('questions_master.*, co_master.*,questions_master.id as q_id');
		$this->db->from('questions_master');
        $this->db->order_by('questions_master.id', 'desc');
        $this->db->join('co_master','co_master.id=questions_master.co_id');
		$this->db->where('questions_master.doctor_id', $doctor_id);

        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new questions_master
     */
    function add_questions_master($params)
    {
        $this->db->insert('questions_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update questions_master
     */
    function update_questions_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('questions_master',$params);
    }
    
    /*
     * function to delete questions_master
     */
    function delete_questions_master($id)
    {
        return $this->db->delete('questions_master',array('id'=>$id));
    }

    function get_co_question($co_id){
		$this->db->order_by('id', 'desc');
		$this->db->where('co_id', $co_id);
		return $this->db->get('questions_master')->result_array();
	}
	function get_question_suggestion($question){
		$this->db->select('suggestions_master.suggestions');
		$this->db->from('questions_master');
		$this->db->join('suggestions_master','suggestions_master.question_id=questions_master.id');
		$this->db->where('questions_master.question', $question);

		return $this->db->get()->result_array();
	}
}
