<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Suggestions_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}

	public function remove_old_suggestions($question_id)
	{
		return $this->db->delete('suggestions_master',array('question_id'=>$question_id));

	}

	public function add_suggestions($suggestions)
	{
		$this->db->insert_batch('suggestions_master', $suggestions);
	}

	public function get_all($question_id)
	{
		$this->db->where('question_id', $question_id);
		return $this->db->get('suggestions_master')->result_array();
	}


}
