<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Table_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get table_master by id
     */
    function get_table_master($id,$doctor_id)
    {
        return $this->db->get_where('table_master',array('id'=>$id,'doctor_id'=>$doctor_id))->row_array();
    }
        
    /*
     * Get all table_master
     */
    function get_all_table_master($doctor_id)
    {
        $this->db->order_by('id', 'desc');
		$this->db->where('doctor_id', $doctor_id);
        return $this->db->get('table_master')->result_array();
    }
        
    /*
     * function to add new table_master
     */
    function add_table_master($params)
    {
        $this->db->insert('table_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update table_master
     */
    function update_table_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('table_master',$params);
    }
    
    /*
     * function to delete table_master
     */
    function delete_table_master($id)
    {
        return $this->db->delete('table_master',array('id'=>$id));
    }
}
